
language: node_js

node_js:
  - "14.17.0"

addons:
  sonarcloud:
    organization: "vvenega"
    token:
      secure: "jKmta1waeCymVFMmz3Z/7kNqqckEJ7ILdVkf4MKqo6ksrYY8BeonJuItSoHbPAQmim/UykqHtfQPI/FwZWCQ/gW2xxOjiROnQQmHuUAfi0gclhIdqvV/ZiATz++HzlV4u1DL/5QItsy7vd2TrMRVOKvQ6xmGMAPULds7UdAJPoreVXmNb0BHeGu/ANRIETA69pG+yRgnh579wer8WutDEw0kuxzndTBrwY7XkpLSn726sn36kMSu9A8pJYeKz6/TyLgs4/xH6bZGVAya/g3+lMhe7QzWDMJZEJ73J1Ba8USj/vgjnZcZa4GVMqCQPgZIiRgEdDLXfGg1s54zkmLDF58HapAozV3OJhXMTjy8MoyGiAYjGD8WSVrTwZixgnA98kuoQpatLJdH2Fp26VXbghyvydtW2eK34uljZG2bjtigVOJ9qGGni8YPIVujrmFmUaZfy7fiGCYpI9RqQ184miQUqtFgfO1v3hnKGkkpCBu60zRidFA6c02Gt32c00Sgk3AnWlW4KEmRwoYj17ioim0yqrcmAiv67ZRCw/oIdIs2f9sEW+wEXQIHwci1WEgpeExBNVsfppu24FCpmwD2QMjoBVgiU1HSiRukO7eNbt6bffXoRqexylowvlNtJTf0GZ5IFtTk46mOApCSMgpz3gJGjN2XaErlzEEdyZ0jgBY="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
