addons:
  sonarcloud:
    organization: "vvenega"
    token:
      secure: "k+sRjxL1ea8VK0A6VFC/6dLb8Aq/6RTVM90j3boAArd5KjFmjfwfeGXiMKiNq9qwFOKKVSk/aBQpUbnvzNwvgb5P8XVqQwHGG76aN2v8v/u20+e3Bsp0R16U9lYPSmwhUoBTmzip6wv129ri2ESC/2Fny/UN0cZ3CidIZBl8FuoTiF+soiTo8aWOVMIiL2Jb6jvRUB0LimgBeM243qqS+qKMGMBn/F8mngj+F581tSC9jBKNPOHc4RgiWADJnxTiqFExUPrxJOT7K1vH6n07t2aS8jJmWeF5P86CZkPzybifG3rIsi9SV+48dGadX89v/k+oOy4V8pDTy+HS0bCmGfcdqOCXKAwcAlEbCZVli+ppn4QtEqhNJ5Vj2azU2Zn5LCWmGHBOuXuc1T6o3T3AF/GHZMei3+XpOfucyWj4GT2dDgbc6B55Kz0zA8+svF7/jSNH/cZLM/4hDlXUn2L9432c6TQiE2BhmuGL5vSZ0JTtWmcj+5fZ0kdK8JCGH2odLvL1ud2QXKtC8CVTLhDlmE59v530XmXBcbMb7we3tq1kfLbK+ZDOy4K0NAJ6XLQcCHZ72xWTTdMpiCyjYEb5h2r4jIPmprsIIK7lRYwIXtmMib2v8xdXAMry4vle4PubOIy7Ywnd+uOoxwwQTUgYwYFVy2Uz8HoxMMEFCqyCgeU="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
