addons:
  sonarcloud:
    organization: "vvenega"
    token:
      secure: "d3txbvekJbBTht3FIWdMqHbrlah+7+D4ZlEj6i26HomLoyyvKmoKejhErZxSKjnkpgEResjfHQ8efOfIBLxBZoa3CS7Tg5sfz5u4LS1j6ug0Px5rgpfjhRu6ZItEaanK+P2fxxnZZmKIzskv9ea0Gd7zbuRL6DdNPxx8DjhoBfOU05d7hToMFLfztf3MItgHBnFZvJa0+gyQxKLI8AvB154sfcCSZWsaq1zLucwn8/Edkadc9bmdCEDd7lGXrSbVshhe89v2XgbFoG9ZiFyKcrPr7qC1YyqqMPBcB356XBALAdVwD4DQ06rwSmGZktmUrmPQqNw6s5RgAL4f8UogMpCwN3YZWFHlWs52O8zc+7lbesuYMdDMrjTzvKmAkSszf+p1gE4vBG3/AOR9i/KEmVuf/0YTNyqMY7mURi/qRGpbWaZGkTjQgGuVbZl7XzqVYm2vRSCBz9FHUgJf909FX8xiZKmJ85Mjh/q4fX4wPP9Cp4yt/ITWS5dTsnnMFoF5pj7w7aEsFDnhvavWeaXxgtTx2J9RYni8u4xQgQtJlzoy7p+gRuJFqnuL4LEnGkUKMhJJ04w4PoizCrZ1Z0+ckGEG6KsSlUoyEZVE7XKgR5uBSya0Wzv+lzlT58J+lBZ47RWcc3rPdCScZ7HWfvR5Qjmf6A4a0eqPb2WMj8fhgOc="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
