addons:
  sonarcloud:
    organization: "vvenega"
    token:
      secure: "QnSwNSF/Ini1TY9I55vHiQE87q6f65Zpkzb1TK52CDOsNiUws2scNjs1mmQbX09TsyDsLmJyET8BgOEuxyz122y/6fQ7EaA0irHDkvy4Zg37faCmC14x8VK6BSWZB7AXNFlyQTo1ZYtPAhlF1+UghBsj07Ma6Td+2qW759EW1Bi/PbJWrvZD1PXEHDo8MkkthmxU3lYhW8Bv0goUYFHt4Y6O/BGjbx49XSW+fJmymZCzBrt0Jh/ehusrdQlhOiaOt2zqeRPIDcVYraf80J6y9ryeyTJ9AlGIwkjV5OhSNp4apD7oJL5MGsKzzHOkd4Nsmf0ZrAeWunxrngwFdhk0xPJM7qMfOEUGiW8udgRqk+OVCPpdvEpqjeLOQgOoPABcdDBEbPFzNrSNxqtvPfDLCGtdnlILlElFM7vclfygcwMzSeuswQY4PyUKrlHA9rEwtNSQJd3OYfHudoXip5eRgzfuoZNyalqCgjr1L39bt69/Qe+CCB7tl2cCSnVmS3cKY0nIGliF4ngcQmDEhxSsLQWUQAKi7/Yd17qdTyYy//jvfBNStImTOGOhlxrt3vlTMvn7PV4fJ/aSt5suEC4cZpBjYZocD0i/uy0CYb5kPn6VfvrX8Z4KKR/NdmZlXAO1kMT0KUvyP6YsIUDH38Lu7mEC+YIhG6nd3fPM6bGgKCU="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
